import { useMemo, useState } from 'react'
import * as Dialog from '@radix-ui/react-dialog'
import { Activity, BarChart3, CircleDollarSign, Database, FlaskConical, Gauge, MousePointerClick, Send, ShieldCheck, Users, X } from 'lucide-react'
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { MetricCard } from './components/MetricCard'
import { useDashboard } from './hooks/useDashboard'
import type { Campaign, DataLimits, DashboardData, Pilot, SimulationData } from './types/api'
import './App.css'

type Tab = 'Обзор' | 'Портфель кампаний' | 'Работа агента' | 'Симуляция' | 'Данные и лимиты'
const tabs: Tab[] = ['Обзор', 'Портфель кампаний', 'Работа агента', 'Симуляция', 'Данные и лимиты']
const money = new Intl.NumberFormat('ru-RU', { maximumFractionDigits: 0 })
const million = (value: number) => `+${(value / 1_000_000).toFixed(2).replace('.', ',')} млн`
const channelLabels: Record<string, string> = { Push: 'Пуш', SMS: 'SMS', 'Digital ads': 'Цифровая реклама', Call: 'Звонок' }
const confidenceLabels: Record<string, string> = { High: 'Высокая', Medium: 'Средняя', Testing: 'Проверяем' }
const statusLabels: Record<string, string> = { Ready: 'Готово', Testing: 'Проверяем' }

function App() {
  const [tab, setTab] = useState<Tab>('Обзор')
  const { dashboard, campaigns, pilots, simulation, limits, isDemo, isLoading, runSimulation } = useDashboard()
  const [simulationState, setSimulationState] = useState<SimulationData>()
  if (isLoading || !dashboard || !simulation || !limits) return <div className="loading-screen"><span className="bee-loader" />Загружаем данные кампаний…</div>
  const activeSimulation = simulationState ?? simulation
  const run = async () => setSimulationState((await runSimulation()).data)
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><i /><i /><i /></span><div><b>sergeek</b><small>АГЕНТ КАМПАНИЙ</small></div></div><nav>{tabs.map((item, index) => <button className={tab === item ? 'nav-item active' : 'nav-item'} onClick={() => setTab(item)} key={item} type="button"><span>0{index + 1}</span>{item}</button>)}</nav><div className="side-status"><span className="pulse" />Агент на связи <small>Локальная рабочая среда</small></div></aside><main className="main"><header className="topbar"><div><p className="eyebrow">ТАРИФНЫЕ МАРКЕТИНГОВЫЕ КАМПАНИИ BEELINE</p><h1>{tab}</h1></div><div className="topbar-side">{isDemo && <span className="demo-badge">Демо-данные</span>}<span className="pass-badge"><ShieldCheck size={15} /> {dashboard.status}</span><div className="avatar">Я</div></div></header>{tab === 'Обзор' && <Overview dashboard={dashboard} />}{tab === 'Портфель кампаний' && <Portfolio campaigns={campaigns} />}{tab === 'Работа агента' && <Intelligence pilots={pilots} />}{tab === 'Симуляция' && <Simulation simulation={activeSimulation} onRun={run} />}{tab === 'Данные и лимиты' && <Limits limits={limits} />}</main></div>
}

function Overview({ dashboard }: { dashboard: DashboardData }) {
  const metrics = [['Базовый ARPU', money.format(dashboard.baselineArpu), 'суммарно до кампаний', CircleDollarSign], ['Чистый эффект', million(dashboard.campaignNetGain), 'локальная mock-симуляция', Activity], ['Использованный бюджет', `${money.format(dashboard.budgetUsed)} / ${money.format(dashboard.budgetLimit)}`, 'в рамках ограничения', Gauge], ['Контакты', `${money.format(dashboard.contactsUsed)} / ${money.format(dashboard.contactsLimit)}`, 'клиентов в охвате', Users], ['Пилоты', `${dashboard.pilotsUsed} / ${dashboard.pilotsLimit}`, '10 первичных + 4 подтверждающих', FlaskConical], ['Финальные кампании', `${dashboard.finalCampaigns} / ${dashboard.finalCampaignLimit}`, 'только с положительным эффектом', Send]] as const
  return <><section className="hero"><div><p className="eyebrow dark">АДАПТИВНОЕ ПЛАНИРОВАНИЕ В УСЛОВИЯХ НЕОПРЕДЕЛЁННОСТИ</p><h2>Каждая кампания<br /><em>должна себя оправдать.</em></h2><p>Sergeek проверяет идеи на пилотах и учитывает экономику каналов, чтобы собрать безопасный портфель в рамках бюджета.</p></div><div className="hero-orbit"><b>{million(dashboard.campaignNetGain)}</b><span>ожидаемый чистый эффект</span></div></section><section className="metrics-grid">{metrics.map(([label, value, note, icon], index) => <MetricCard key={label} label={label} value={value} note={note} icon={icon} emphasis={index === 1} />)}</section><section className="process"><p className="eyebrow">КАК АГЕНТ ПРИНИМАЕТ РЕШЕНИЕ</p><div>{['Исторические данные', 'Гипотезы перехода', 'Пуш-пилоты', 'Поправка на уверенность', 'Выбор канала', 'Финальный портфель'].map((item, index) => <span key={item}><b>0{index + 1}</b>{item}</span>)}</div></section><section className="charts-grid"><ChartCard title="Бюджет по каналам" note="Локальная mock-симуляция"><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={dashboard.channelBudget} dataKey="value" nameKey="name" innerRadius={52} outerRadius={82} paddingAngle={4}>{dashboard.channelBudget.map((_, index) => <Cell fill={['#ffd900', '#252525', '#9c9c95'][index]} key={index} />)}</Pie><Tooltip formatter={(value) => `${money.format(Number(value))} ₸`} /></PieChart></ResponsiveContainer></ChartCard><ChartCard title="Ожидаемый чистый эффект" note="После стоимости коммуникации"><ResponsiveContainer width="100%" height={220}><BarChart data={dashboard.campaignNet}><XAxis dataKey="name" tickLine={false} axisLine={false} tick={{ fontSize: 10 }} /><YAxis hide /><Tooltip formatter={(value) => `${value} тыс. ₸`} /><Bar dataKey="value" radius={[6, 6, 0, 0]} fill="#ffd900" /></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Охват аудитории" note={`Лимит контактов: ${money.format(dashboard.contactsLimit)}`}><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={dashboard.audienceCoverage} dataKey="value" innerRadius={52} outerRadius={82}>{dashboard.audienceCoverage.map((_, index) => <Cell fill={index === 0 ? '#45a869' : '#e8e8e2'} key={index} />)}</Pie><Tooltip formatter={(value) => money.format(Number(value))} /></PieChart></ResponsiveContainer><div className="coverage-value"><b>{money.format(dashboard.contactsUsed)}</b><span>клиентов в охвате</span></div></ChartCard></section><p className="simulation-caption">Все результаты получены в локальной mock-модели и не гарантируют результат на скрытой модели жюри.</p></>
}

function Portfolio({ campaigns }: { campaigns: Campaign[] }) {
  const [channel, setChannel] = useState('Все'); const [segment, setSegment] = useState('Все'); const [search, setSearch] = useState(''); const [sortBy, setSortBy] = useState<'expectedNetGain' | 'audienceSize'>('expectedNetGain'); const [selected, setSelected] = useState<Campaign | null>(null)
  const filtered = useMemo(() => campaigns.filter((item) => (channel === 'Все' || item.channel === channel) && (segment === 'Все' || item.arpuSegment === segment) && item.name.toLowerCase().includes(search.toLowerCase())).sort((a, b) => b[sortBy] - a[sortBy]), [campaigns, channel, search, segment, sortBy])
  return <><section className="page-intro"><p className="eyebrow">ФИНАЛЬНЫЕ РЕКОМЕНДАЦИИ</p><h2>Портфель кампаний</h2><p>В портфель попадают только предложения с положительным наблюдаемым эффектом.</p></section><section className="filter-row"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Найти кампанию…" /><select value={channel} onChange={(event) => setChannel(event.target.value)}><option>Все</option><option value="Push">Пуш</option><option>SMS</option><option value="Digital ads">Цифровая реклама</option><option value="Call">Звонок</option></select><select value={segment} onChange={(event) => setSegment(event.target.value)}><option>Все</option><option>Высокий ARPU</option><option>Средний ARPU</option><option>Низкий ARPU</option></select><button onClick={() => setSortBy(sortBy === 'expectedNetGain' ? 'audienceSize' : 'expectedNetGain')} type="button">Сортировка: {sortBy === 'expectedNetGain' ? 'эффект' : 'охват'}</button></section><section className="table-card"><div className="table-scroll"><table><thead><tr><th>Кампания</th><th>Текущий тариф</th><th>Сегмент ARPU</th><th>Целевой тариф</th><th>Канал</th><th>Аудитория</th><th>Стоимость</th><th>Валовый эффект</th><th>Чистый эффект</th><th>Уверенность</th><th>Статус</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id} onClick={() => setSelected(item)}><td><b>{item.name}</b><small>Кампания {item.id.replace('C-', '')}</small></td><td>{item.currentTariff}</td><td>{item.arpuSegment}</td><td>{item.targetTariff}</td><td><ChannelBadge channel={item.channel} /></td><td>{money.format(item.audienceSize)}</td><td>{money.format(item.communicationCost)} ₸</td><td>+{money.format(item.expectedGrossLift)} ₸</td><td className="positive">+{money.format(item.expectedNetGain)} ₸</td><td><span className={`confidence ${item.confidence.toLowerCase()}`}>{confidenceLabels[item.confidence]}</span></td><td><span className={item.status === 'Ready' ? 'ready-dot' : 'testing-dot'}>{statusLabels[item.status]}</span></td></tr>)}</tbody></table></div></section>{selected && <CampaignDialog campaign={selected} onClose={() => setSelected(null)} />}</>
}

function Intelligence({ pilots }: { pilots: Pilot[] }) { const confidence = pilots.map((pilot) => ({ name: pilot.id.replace('P-', ''), value: pilot.confidence })); return <><section className="page-intro"><p className="eyebrow">ЛОГИКА, А НЕ МАГИЯ</p><h2>Работа агента</h2><p>Агент проходит через 15 тарифных гипотез, контролируемые пилоты и ограничения портфеля.</p></section><section className="stage-grid">{[['15', 'тарифных гипотез'], ['10 × 120', 'первичных пуш-пилотов'], ['4 × 200', 'подтверждающих пилота'], ['1', 'оптимальный портфель']].map(([value, label]) => <article key={label}><b>{value}</b><span>{label}</span></article>)}</section><section className="intelligence-grid"><ChartCard title="Уверенность по пилотам" note="Взвешенное среднее, стандартная ошибка и нижняя граница"><ResponsiveContainer width="100%" height={245}><BarChart data={confidence}><XAxis dataKey="name" tickLine={false} axisLine={false} /><YAxis domain={[0, 100]} tickLine={false} axisLine={false} /><Tooltip /><Bar dataKey="value" radius={[6, 6, 0, 0]} fill="#45a869" /></BarChart></ResponsiveContainer></ChartCard><article className="why-card"><p className="eyebrow">ПОЧЕМУ ВЫБРАНА КАМПАНИЯ</p><h3>Лучшее предложение</h3><p>Кампания сохраняет положительную нижнюю границу эффекта после подтверждения и не пересекается с другой аудиторией.</p><div><span>Наблюдаемый эффект</span><b>Положительный</b></div><div><span>Выбранный канал</span><b>Оптимальный</b></div></article></section><section className="timeline-card"><div><p className="eyebrow">ТАЙМЛАЙН ПИЛОТОВ</p><h3>Сначала доказательство, затем масштаб</h3></div>{pilots.map((pilot) => <article className="pilot-row" key={pilot.id}><span className={pilot.status === 'Completed' ? 'pilot-icon done' : 'pilot-icon'}><FlaskConical size={15} /></span><div><b>{pilot.title}</b><small>Пилот {pilot.id.replace('P-', '')} · {pilot.phase === 'Initial' ? 'первичная проверка' : 'подтверждение'} · {money.format(pilot.audience)} клиентов</small></div><span>{pilot.result}</span><strong>{pilot.confidence}% уверенность</strong></article>)}</section><section className="decision-chain">{['Взвешенное среднее', 'Стандартная ошибка', 'Нижняя граница', 'Исключить пересечения', 'Подобрать канал', 'Собрать портфель'].map((step, index) => <span key={step}><b>{index + 1}</b>{step}</span>)}</section></>
}

function Simulation({ simulation, onRun }: { simulation: SimulationData; onRun: () => void }) { return <><section className="simulation-hero"><div><p className="eyebrow dark">ЛОКАЛЬНАЯ ПРОВЕРКА</p><h2>Устойчивый результат<br />при неопределённости.</h2><p>Mock-симуляция проверяет механику и устойчивость. На финальной оценке будут скрытые эффекты аудитории.</p><button onClick={onRun} type="button"><MousePointerClick size={16} /> Запустить симуляцию</button></div><div className="pass-ring"><span>{simulation.profitableRuns}/{simulation.totalRuns}</span><small>прибыльных локальных прогонов</small><b>PASS</b></div></section><section className="metrics-grid four"><MetricCard label="Медианный эффект" value={million(simulation.medianNet)} note="локальная mock-симуляция" icon={BarChart3} emphasis /><MetricCard label="Минимальный эффект" value={million(simulation.minimumNet)} note="худший прогон" icon={Activity} /><MetricCard label="Максимальный эффект" value={million(simulation.maximumNet)} note="лучший прогон" icon={Activity} /><MetricCard label="Контрольный seed" value={million(simulation.controlSeedNet)} note="проверка воспроизводимости" icon={ShieldCheck} /></section><section className="intelligence-grid"><ChartCard title="Распределение результатов" note={`${simulation.totalRuns} локальных прогонов`}><ResponsiveContainer width="100%" height={245}><BarChart data={simulation.distribution}><XAxis dataKey="bin" tickLine={false} axisLine={false} /><YAxis hide /><Tooltip /><Bar dataKey="count" fill="#ffd900" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Сравнение портфелей" note="Ожидаемый чистый эффект, млн ₸"><ResponsiveContainer width="100%" height={245}><BarChart data={simulation.comparison}><XAxis dataKey="name" tickLine={false} axisLine={false} /><YAxis /><Tooltip /><Bar dataKey="value" fill="#252525" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></ChartCard></section><p className="simulation-caption">Mock-симуляция проверяет механику и устойчивость. Финальная оценка использует скрытые эффекты аудитории.</p></> }

function Limits({ limits }: { limits: DataLimits }) { const rows = [['Абоненты', money.format(limits.subscribers)], ['Базовый ARPU', money.format(limits.baselineArpu)], ['Бюджет', `${money.format(limits.budget)} ₸`], ['Лимит контактов', money.format(limits.contacts)], ['Лимит пилотов', `${limits.pilots} пилотов`], ['Размер пилота', `до ${limits.pilotSize}`], ['Финальные кампании', `до ${limits.finalCampaigns}`], ['Размер кампании', `до ${money.format(limits.campaignSize)}`]]; return <><section className="page-intro"><p className="eyebrow">ОГРАНИЧЕНИЯ ЗАДАЮТ ПРАВИЛА</p><h2>Данные и лимиты</h2><p>Оптимизатор не рекомендует портфель, который превышает ограничения среды.</p></section><section className="limits-grid">{rows.map(([label, value], index) => <article key={label}><span>0{index + 1}</span><p>{label}</p><b>{value}</b></article>)}</section><section className="table-card"><div className="channel-heading"><div><p className="eyebrow">ЭКОНОМИКА КАНАЛОВ</p><h3>Стоимость и множитель конверсии</h3></div><Database size={22} /></div><table className="channel-table"><thead><tr><th>Канал</th><th>Стоимость коммуникации</th><th>Множитель конверсии</th><th>Роль в оптимизации</th></tr></thead><tbody>{limits.channels.map((item) => <tr key={item.name}><td><ChannelBadge channel={item.name} /></td><td>{item.cost === 0 ? 'Бесплатно' : `${item.cost} ₸ / контакт`}</td><td><b>{item.multiplier}</b></td><td>{item.name === 'Push' ? 'Базовый недорогой канал' : item.name === 'Call' ? 'Дорогой канал для высокого интереса' : 'Канал для оптимизации портфеля'}</td></tr>)}</tbody></table></section></> }

function ChartCard({ title, note, children }: { title: string; note: string; children: React.ReactNode }) { return <article className="chart-card"><div><h3>{title}</h3><p>{note}</p></div>{children}</article> }
function ChannelBadge({ channel }: { channel: string }) { return <span className={`channel-badge ${channel.toLowerCase().replace(' ', '-')}`}>{channelLabels[channel] ?? channel}</span> }
function CampaignDialog({ campaign, onClose }: { campaign: Campaign; onClose: () => void }) { return <Dialog.Root open onOpenChange={(open) => !open && onClose()}><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="dialog"><Dialog.Close className="dialog-close"><X size={18} /></Dialog.Close><p className="eyebrow">ДЕТАЛИ КАМПАНИИ</p><Dialog.Title>{campaign.name}</Dialog.Title><Dialog.Description>{campaign.rationale}</Dialog.Description><div className="dialog-stats"><span><small>Ожидаемый чистый эффект</small><b>+{money.format(campaign.expectedNetGain)} ₸</b></span><span><small>Аудитория</small><b>{money.format(campaign.audienceSize)}</b></span><span><small>Канал</small><ChannelBadge channel={campaign.channel} /></span></div><div className="dialog-route"><span>{campaign.currentTariff}</span><b>→</b><span>{campaign.targetTariff}</span></div></Dialog.Content></Dialog.Portal></Dialog.Root> }
export default App
